# Generated by Django 4.2 on 2023-04-10 18:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id_categoria",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("nombre_categoria", models.CharField(max_length=30)),
                ("descripcion_categoria", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id_pedido",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("fecha_registro", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("VND", "Vendido"), ("EES", "En espera")],
                        default="EES",
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id_producto",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("precio", models.FloatField()),
                ("descripcion_producto", models.TextField(blank=True, null=True)),
                ("descuento", models.FloatField(default=0.0)),
                ("cantidad_disponible", models.IntegerField(default=0)),
                ("valorInv", models.FloatField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id_categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_sig.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductoEnSucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valorUnitario", models.FloatField()),
                ("cantidad", models.IntegerField()),
                ("fecha_registro", models.DateTimeField()),
                (
                    "id_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_sig.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "pedido_venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="pedido_vendido",
                        serialize=False,
                        to="api_sig.pedido",
                    ),
                ),
                ("total", models.FloatField()),
                ("iva", models.FloatField()),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id_sucursal",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("nombre_sucursal", models.CharField(max_length=50)),
                ("direccion", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "productos",
                    models.ManyToManyField(
                        related_name="sucursal_productos",
                        through="api_sig.ProductoEnSucursal",
                        to="api_sig.producto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productoensucursal",
            name="id_sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prods_sucursal",
                to="api_sig.sucursal",
            ),
        ),
        migrations.CreateModel(
            name="ProductoDanado",
            fields=[
                (
                    "id_productoDanado",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("fecha_registro", models.DateField()),
                ("detalle", models.CharField(max_length=100)),
                ("cantidad", models.IntegerField()),
                (
                    "id_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_sig.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id_movimiento",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("fecha_registro", models.DateTimeField()),
                ("detalle", models.CharField(max_length=30)),
                ("valorUnitario", models.FloatField()),
                ("cantidad", models.IntegerField()),
                ("total", models.FloatField()),
                ("tipo", models.CharField(max_length=1)),
                (
                    "id_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_sig.producto",
                    ),
                ),
                (
                    "id_sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movs",
                        to="api_sig.sucursal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineaPedido",
            fields=[
                (
                    "id_linea_pedido",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("precioUni", models.FloatField()),
                ("descuento", models.FloatField(default=0)),
                ("importe", models.FloatField()),
                ("cantidad", models.IntegerField()),
                ("total", models.FloatField()),
                (
                    "movimiento",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveBigIntegerField(),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "id_pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="api_sig.pedido",
                    ),
                ),
                (
                    "id_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_sig.producto",
                    ),
                ),
            ],
        ),
    ]
