# Generated by Django 4.2 on 2023-06-05 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id_categoria",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("nombre_categoria", models.CharField(max_length=30)),
                ("descripcion_categoria", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                ("variable", models.TextField(primary_key=True, serialize=False)),
                ("value", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id_producto",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("precio", models.FloatField()),
                ("descripcion_producto", models.TextField(blank=True, null=True)),
                ("descuento", models.FloatField(default=0.0)),
                ("cantidad_disponible", models.IntegerField(default=0)),
                ("valorInv", models.FloatField(default=0)),
                (
                    "id_categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_sig.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id_sucursal",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("nombre_sucursal", models.CharField(max_length=50)),
                ("direccion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductoDanado",
            fields=[
                (
                    "id_productoDanado",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("fecha_registro", models.DateField()),
                ("detalle", models.CharField(max_length=100)),
                ("cantidad", models.IntegerField()),
                (
                    "id_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_sig.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id_movimiento",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("fecha_registro", models.DateTimeField()),
                ("detalle", models.CharField(max_length=30)),
                ("valorUnitario", models.FloatField()),
                ("cantidad", models.IntegerField()),
                ("total", models.FloatField()),
                ("tipo", models.CharField(max_length=1)),
                (
                    "id_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_sig.producto",
                    ),
                ),
                (
                    "id_sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movs",
                        to="api_sig.sucursal",
                    ),
                ),
            ],
        ),
    ]
