# Generated by Django 4.2 on 2023-04-10 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_sig", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="sucursal",
            name="is_active",
        ),
    ]
